/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddonIcon: typeof import('./src/components/AddonIcon.vue')['default']
    InstalledList: typeof import('./src/components/InstalledList.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SettingsBar: typeof import('./src/components/SettingsBar.vue')['default']
  }
}
